function bsn(par_n,par_f,symbol,x, sensin_path, out_data_path)
SFTMP   = x(cellfun(@(x) isequal(x, 'SFTMP'), symbol));
SMTMP   = x(cellfun(@(x) isequal(x, 'SMTMP'), symbol));
SMFMX   = x(cellfun(@(x) isequal(x, 'SMFMX'), symbol));
SMFMN   = x(cellfun(@(x) isequal(x, 'SMFMN'), symbol));
TIMP    = x(cellfun(@(x) isequal(x, 'TIMP'), symbol));
ESCO    = x(cellfun(@(x) isequal(x, 'ESCO'), symbol));
EPCO    = x(cellfun(@(x) isequal(x, 'EPCO'), symbol));
EVLAI   = x(cellfun(@(x) isequal(x, 'EVLAI'), symbol));
SURLAG  = x(cellfun(@(x) isequal(x, 'SURLAG'), symbol));
ADJ_PKR = x(cellfun(@(x) isequal(x, 'ADJ_PKR'), symbol));
DEPIMP_BSN=x(cellfun(@(x) isequal(x, 'DEPIMP_BSN'), symbol));
PRF     = x(cellfun(@(x) isequal(x, 'PRF'), symbol));
SPCON   = x(cellfun(@(x) isequal(x, 'SPCON'), symbol));
SPEXP   = x(cellfun(@(x) isequal(x, 'SPEXP'), symbol));
RCN     = x(cellfun(@(x) isequal(x, 'RCN'), symbol));
CMN     = x(cellfun(@(x) isequal(x, 'CMN'), symbol));
NPERCO  = x(cellfun(@(x) isequal(x, 'NPERCO'), symbol));
PPERCO  = x(cellfun(@(x) isequal(x, 'PPERCO'), symbol));
PHOSKD  = x(cellfun(@(x) isequal(x, 'PHOSKD'), symbol));
PSP     = x(cellfun(@(x) isequal(x, 'PSP'), symbol));
RSDCO   = x(cellfun(@(x) isequal(x, 'RSDCO'), symbol));
PERCOP  = x(cellfun(@(x) isequal(x, 'PERCOP'), symbol));
EVRCH   = x(cellfun(@(x) isequal(x, 'EVRCH'), symbol));
CDN     = x(cellfun(@(x) isequal(x, 'CDN'), symbol));
SDNCO   = x(cellfun(@(x) isequal(x, 'SDNCO'), symbol));
SNOCOVMX= x(cellfun(@(x) isequal(x, 'SNOCOVMX'), symbol));
SNO50COV= x(cellfun(@(x) isequal(x, 'SNO50COV'), symbol));
ICN     = x(cellfun(@(x) isequal(x, 'ICN'), symbol));
CNCOEF  = x(cellfun(@(x) isequal(x, 'CNCOEF'), symbol));
MSK_CO1  = x(cellfun(@(x) isequal(x, 'MSK_CO1'), symbol));
MSK_CO2  = x(cellfun(@(x) isequal(x, 'MSK_CO2'), symbol));
MSK_X  = x(cellfun(@(x) isequal(x, 'MSK_X'), symbol));

N_UPDIS  = x(cellfun(@(x) isequal(x, 'N_UPDIS'), symbol));
FIXCO  = x(cellfun(@(x) isequal(x, 'FIXCO'), symbol));
NFIXMX  = x(cellfun(@(x) isequal(x, 'NFIXMX'), symbol));
ANION_EXCL_BSN  = x(cellfun(@(x) isequal(x, 'ANION_EXCL_BSN'), symbol));

file_read = [sensin_path '\basins.bsn'];
file_write = [out_data_path '\basins.bsn'];
delete(file_write);
fid1=fopen(file_read,'r');
fid2=fopen(file_write,'w');

L=0;
while feof(fid1)==0;
    L=L+1;
    line=fgets(fid1);
    if L==4 && par_f(cellfun(@(x) isequal(x, 'SFTMP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n',SFTMP,'| SFTMP : Snowfall temperature [ºC]');
    elseif L==5 && par_f(cellfun(@(x) isequal(x, 'SMTMP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SMTMP ,'| SMTMP : Snow melt base temperature [ºC]');
    elseif L==6 && par_f(cellfun(@(x) isequal(x, 'SMFMX'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SMFMX ,'| SMFMX : Melt factor for snow on June 21 [mm H2O/ºC-day]');
    elseif L==7 && par_f(cellfun(@(x) isequal(x, 'SMFMN'), symbol))==1;
        if par_f(cellfun(@(x) isequal(x, 'SMFMX'), symbol))==1 && SMFMN > SMFMX
            SMFMN = SMFMX;
        end
        fprintf(fid2,'%16.3f\t  %s\n', SMFMN ,'| SMFMN : Melt factor for snow on December 21 [mm H2O/ºC-day]');
    elseif L==8 && par_f(cellfun(@(x) isequal(x, 'TIMP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', TIMP ,'| TIMP : Snow pack temperature lag factor');
    elseif L==9 && par_f(cellfun(@(x) isequal(x, 'SNOCOVMX'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SNOCOVMX ,'| SNOCOVMX : Minimum snow water content that corresponds to 100% snow cover [mm]');
    elseif L==10 && par_f(cellfun(@(x) isequal(x, 'SNO50COV'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SNO50COV ,'| SNO50COV : Fraction of snow volume represented by SNOCOVMX that corresponds to 50% snow cover');
    elseif L==13 && par_f(cellfun(@(x) isequal(x, 'ESCO'), symbol))==1;
            fprintf(fid2,'%16.3f\t  %s\n', ESCO,'| ESCO: soil evaporation compensation factor');
    elseif L==14 && par_f(cellfun(@(x) isequal(x, 'EPCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', EPCO,'| EPCO: plant water uptake compensation factor');
    elseif L==15 && par_f(cellfun(@(x) isequal(x, 'EVLAI'), symbol))==1;
        EVLAI=str2double(strtok(line))*(1+EVLAI);
        fprintf(fid2,'%16.3f\t  %s\n', EVLAI ,'| EVLAI : Leaf area index at which no evaporation occurs from water surface [m2/m2]');
    elseif L==20 && par_f(cellfun(@(x) isequal(x, 'SURLAG'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SURLAG ,'| SURLAG : Surface runoff lag time [days]');
    elseif L==21 && par_f(cellfun(@(x) isequal(x, 'ADJ_PKR'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', ADJ_PKR ,'| ADJ_PKR : Peak rate adjustment factor for sediment routing in the subbasin (tributary channels)');
    elseif L==22 && par_f(cellfun(@(x) isequal(x, 'PRF'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', PRF ,'| PRF : Peak rate adjustment factor for sediment routing in the main channel');
    elseif L==23 && par_f(cellfun(@(x) isequal(x, 'SPCON'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SPCON ,'| SPCON : Linear parameter for calculating the maximum amount of sediment that can be reentrained during channel sediment routing ');
    elseif L==24 && par_f(cellfun(@(x) isequal(x, 'SPEXP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SPEXP ,'| SPEXP : Exponent parameter for calculating sediment reentrained in channel sediment routing ');
    elseif L==26 && par_f(cellfun(@(x) isequal(x, 'RCN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', RCN,'| RCN: nitrogen in rainfall (ppm)');
    elseif L==27 && par_f(cellfun(@(x) isequal(x, 'CMN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', CMN ,'| CMN : Rate factor for humus mineralization of active organic nitrogen');
    elseif L==28 && par_f(cellfun(@(x) isequal(x, 'N_UPDIS'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', N_UPDIS ,'| N_UPDIS : Nitrogen uptake distribution parameter');                      
    elseif L==30 && par_f(cellfun(@(x) isequal(x, 'NPERCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', NPERCO ,'| NPERCO : Nitrogen percolation coefficient');
    elseif L==31 && par_f(cellfun(@(x) isequal(x, 'PPERCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', PPERCO ,'| PPERCO : Phosphorus percolation coefficient');
    elseif L==32 && par_f(cellfun(@(x) isequal(x, 'PHOSKD'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', PHOSKD ,'| PHOSKD : Phosphorus soil partitioning coefficient');
    elseif L==33 && par_f(cellfun(@(x) isequal(x, 'PSP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', PSP ,'| PSP : Phosphorus sorption coefficient');
    elseif L==34 && par_f(cellfun(@(x) isequal(x, 'RSDCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', RSDCO ,'| RSDCO : Residue decomposition coefficient');
    elseif L==36 && par_f(cellfun(@(x) isequal(x, 'PERCOP'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', PERCOP ,'| PERCOP : Pesticide percolation coefficient');
    elseif L==59 && par_f(cellfun(@(x) isequal(x, 'MSK_CO1'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', EVRCH ,'| MSK_CO1');
    elseif L==60 && par_f(cellfun(@(x) isequal(x, 'MSK_CO2'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', EVRCH ,'| MSK_CO2');
    elseif L==61 && par_f(cellfun(@(x) isequal(x, 'MSK_X'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', EVRCH ,'| MSK_X');        
    elseif L==66 && par_f(cellfun(@(x) isequal(x, 'EVRCH'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', EVRCH ,'| EVRCH : Reach evaporation adjustment factor');
    elseif L==68 && par_f(cellfun(@(x) isequal(x, 'ICN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', ICN,'| ICN');
    elseif L==69 && par_f(cellfun(@(x) isequal(x, 'CNCOEF'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', CNCOEF,'| CNCOEF');
    elseif L==70 && par_f(cellfun(@(x) isequal(x, 'CDN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', CDN,'| CDN');
    elseif L==71 && par_f(cellfun(@(x) isequal(x, 'SDNCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', SDNCO,'| SDNCO');
    elseif L==81 && par_f(cellfun(@(x) isequal(x, 'DEPIMP_BSN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', DEPIMP_BSN,'| DEPIMP_BSN');
     elseif L==88 && par_f(cellfun(@(x) isequal(x, 'FIXCO'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', FIXCO,'| FIXCO : Nitrogen fixation coefficient');       
    elseif L==89 && par_f(cellfun(@(x) isequal(x, 'NFIXMX'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', NFIXMX,'| NFIXMX : Maximum daily-n fixation [kg/ha]');
    elseif L==90 && par_f(cellfun(@(x) isequal(x, 'ANION_EXCL_BSN'), symbol))==1;
        fprintf(fid2,'%16.3f\t  %s\n', ANION_EXCL_BSN,'| ANION_EXCL_BSN : Fraction of porosity from which anions are excluded');                             
    else
        fprintf(fid2,'%s',line);
    end
end
fclose(fid1);
fclose(fid2);
return;