function alter_f=par_alter(file_id,n_sub,sensin_path,out_data_path)
% Read IPEAT_Para.set file,which includes information on parameters sampled.
[par_n,symbol,x0,par_f, lb, ub]=textread([out_data_path '\IPEAT_Para.set'],'%n%s%*s%*s%n%n%n%n','headerlines',2);
par_n=par_n'; x=x0'; par_f=par_f'; 
symbol = upper(symbol);
%% LATER: get the following lines from interface and delete from here
Reservoires = []; % [res_id,ReservoirSubNumber]

%% Change basin-level parameters
% basin-level files: .bsn, .wwq, plant.dat, pest.dat, .res
% Change class of symbol from "Cell" to "char"
ibsn = max(par_f(cellfun(@(x) isequal(x,'CMN'),symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x,'NPERCO'),symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x,'CDN'),symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x,'PPERCO'),symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x,'RSDCO'),symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SFTMP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SPCON'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SPEXP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SURLAG'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ESCO'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ADJ_PKR'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'DEPIMP_BSN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'EPCO'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'EVLAI'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'EVRCH'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PHOSKD'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PERCOP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PRF'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PSP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RCN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SDNCO'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SMFMN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SMFMX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SMTMP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'TIMP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SNOCOVMX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SNO50COV'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ICN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CNCOEF'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'MSK_CO1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'MSK_CO2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'MSK_X'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'N_UPDIS'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'FIXCO'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'NFIXMX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ANION_EXCL_BSN'), symbol)==1)==1);
    
iwwq = max(par_f(cellfun(@(x) isequal(x, 'AI0'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'AI1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'AI2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'MUMAX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'K_N'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'P_N'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RHOQ'), symbol)==1)==1);

icrop = par_f(cellfun(@(x) isequal(x, 'USLE_C'), symbol)==1)==1;

ipest = par_f(cellfun(@(x) isequal(x, 'PEST_EFF'), symbol)==1)==1;

ires  = max(par_f(cellfun(@(x) isequal(x, 'RES_K'), symbol)==1)==1 || ...
            par_f(cellfun(@(x) isequal(x, 'RES_RR'), symbol)==1)==1 || ...
            par_f(cellfun(@(x) isequal(x, 'WURTNF'), symbol)==1)==1 || ...
            par_f(cellfun(@(x) isequal(x, 'EVRSV'), symbol)==1)==1 || ...
            par_f(cellfun(@(x) isequal(x, 'OFLOWMN_FPS'), symbol)==1)==1 || ...
            par_f(cellfun(@(x) isequal(x, 'STARG_FPS'), symbol)==1)==1);
     
if ibsn==1; bsn(par_n, par_f, symbol, x, sensin_path, out_data_path); end
if iwwq==1; wwq(par_n, par_f, symbol, x, sensin_path, out_data_path); end
if icrop==1; crop(symbol, x, sensin_path, out_data_path); end
if ipest==1; pest(symbol, x, sensin_path, out_data_path); end

    
%% Change subbasin-level parameters
% subbasin-level files: .sub, .rte, .swq, lwq, .res
isub=max(par_f(cellfun(@(x) isequal(x, 'CH_KI'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_NI'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_SI'), symbol)==1)==1);

irte=max(par_f(cellfun(@(x) isequal(x, 'CH_COV1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_COV2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_KII'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_NII'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CH_SII'), symbol)==1)==1);

iswq=max(par_f(cellfun(@(x) isequal(x, 'RS1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RS2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RS3'), symbol)==1)==1 || ...        
        par_f(cellfun(@(x) isequal(x, 'RS4'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RS5'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'BC1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'BC2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'BC3'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'BC4'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_REA'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_VOL'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_KOC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_STL'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_RSP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHPST_MIX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SEDPST_CONC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SEDPST_REA'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SEDPST_BRY'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SEDPST_ACT'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PST_DCY_K'), symbol)==1)==1);
    
ilwq = max(par_f(cellfun(@(x) isequal(x, 'IRES1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'IRES2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PSETLR1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PSETLR2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'NSETLR1'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'NSETLR2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CHLAR'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SECCIR'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_ORGP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_SOLP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_ORGN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_NO3'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_NH3'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RES_NO2'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_CONC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_REA'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_VOL'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_KOC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_STL'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_RSP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_MIX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PST_CONC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'PST_REA'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_BRY'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'LKPST_ACT'), symbol)==1)==1);

if isub==1;
    for sub_no=1:n_sub;  
        subid=file_id(sub_no, 9);
        sub(subid, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

if irte==1;
    for sub_no=1:n_sub;  
        subid=file_id(sub_no, 9);
        rte(subid, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

strOrders = [];
if iswq==1;
    load('stream_order.mat');
    for sub_no=1:n_sub;  
        subid=file_id(sub_no, 9);
        strOrder = strOrders(strOrders(:,1) == sub_no,2);
        swq(subid, par_n, par_f, symbol, x, sensin_path, out_data_path, lb, ub, strOrder);
    end
end

if ilwq==1;
    for res_n = 1 : size(Reservoires, 1);
        ReservoirSubNumber = Reservoires(res_n, 2);        
        lwq(par_f, symbol, x, sensin_path, out_data_path, ReservoirSubNumber);
    end
end

if ires==1;
    for res_n = 1 : size(Reservoires, 1);
        ReservoirSubNumber = Reservoires(res_n, 2);        
        res(par_f, symbol, x, sensin_path, out_data_path, ReservoirSubNumber);
    end
end

% Change hru-level parameters
imgt= max(par_f(cellfun(@(x) isequal(x, 'BIOMIX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CN_F'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'USLE_P'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'BIOMIN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'FILTERW'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'DDRAIN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'TDRAIN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GDRAIN'), symbol)==1)==1);
    
ihru=max(par_f(cellfun(@(x) isequal(x, 'ESCO'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'OV_N'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RSDIN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SLOPE'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'CANMX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'DEP_IMP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SLSUBBSN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'POT_FR'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'POT_TILE'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'POT_VOLX'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'POT_VOL'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'POT_NO3L'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'EVPOT'), symbol)==1)==1);

isol=max(par_f(cellfun(@(x) isequal(x, 'SOL_AWC'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SOL_K'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'USLE_K'), symbol)==1)==1|| ...
        par_f(cellfun(@(x) isequal(x, 'SOL_Z'), symbol)==1)==1|| ...
        par_f(cellfun(@(x) isequal(x, 'SOL_ALB'), symbol)==1)==1);

igw = max(par_f(cellfun(@(x) isequal(x, 'ALPHA_BF'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GW_DELAY'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GW_REVAP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GW_SPYLD'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GWHT'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'GWQMN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'RCHRG_DP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'REVEP_MN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SHALLST_N'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'HLIFE_NGW'), symbol)==1)==1);

ichm=max(par_f(cellfun(@(x) isequal(x, 'LABP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ORGN'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'ORGP'), symbol)==1)==1 || ...
        par_f(cellfun(@(x) isequal(x, 'SOLN'), symbol)==1)==1);
    
n_hru=size(file_id, 1);
if imgt==1;
    for hru_no=1:n_hru;
        hruid=file_id(hru_no, 3);
        hru_lnd=upper(file_id{hru_no, 6});
        Soil_type = upper(file_id{hru_no, 8});
        mgt_f(hruid, hru_lnd, Soil_type, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

if ihru==1;
    for hru_no=1:n_hru;
        hruid=file_id(hru_no, 3);
        hru_lnd=upper(file_id{hru_no, 6});
        hru(hruid, hru_lnd, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

if isol==1;
    for hru_no=1:n_hru;
        hruid=file_id(hru_no, 3); 
        hru_lnd=upper(file_id{hru_no, 6});
        sol(hruid, hru_lnd, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

if igw==1;
    for hru_no=1:n_hru;
        hruid=file_id(hru_no, 3);
        hru_lnd=upper(file_id{hru_no, 6});
        gw(hruid, hru_lnd, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

if ichm==1;
    for hru_no=1:n_hru;
        hruid=file_id(hru_no, 3); 
        hru_lnd=upper(file_id{hru_no, 6});
        sol_depth = file_id{hru_no, 11};
        sol_cbn   = file_id{hru_no, 12};
        chm(hruid, hru_lnd, sol_depth, sol_cbn, par_n, par_f, symbol, x, sensin_path, out_data_path);
    end
end

alter_f='altering model parameters completed';